/**
 * This file was autogenerated using the route definitions from the backend.
 */
import { AxiosResponse } from 'axios';
import { Get, Post, Put, withAuth } from './axios';

export const createAppointment = (): Promise<AxiosResponse> =>
  Post(`/appointments`, withAuth());

export const showConferenceData = (id: number): Promise<AxiosResponse> =>
  Get(`/appointments/${id}/conference`, withAuth());

type SwitchConferenceSlideParameters = {
  presentationIndex: number;
};
export const switchConferenceSlide = (
  id: number,
  params: SwitchConferenceSlideParameters,
): Promise<AxiosResponse> =>
  Put(`/appointments/${id}/conference/slide`, params, withAuth());

export const checkAuthStatus = (): Promise<AxiosResponse> =>
  Get(`/auth/status`, withAuth());

type LoginParameters = {
  email: string;
  password: string;
};
export const login = (params: LoginParameters): Promise<AxiosResponse> =>
  Post(`/auth/login`, params, withAuth());

type RegisterParameters = {
  email: string;
  password: string;
  name: string;
};
export const register = (params: RegisterParameters): Promise<AxiosResponse> =>
  Post(`/auth/register`, params, withAuth());

export const indexUsers = (): Promise<AxiosResponse> =>
  Get(`/users`, withAuth());
